In [1]:
import json
import io
import hashlib
import pandas as pd
import pyarrow as pa

In [2]:
df = pd.read_parquet('sales_si_04.parquet')

In [3]:
df.head()

,BOROUGH,NEIGHBORHOOD,BUILDING_CLASS_CATEGORY,TAX_CLASS_BEFORE_SALE,BLOCK,LOT,BUILDING_CLASS_BEFORE_SALE,ADDRESS,APARTMENT_NUMBER,ZIP_CODE,...,COMMERCIAL_UNITS,TOTAL_UNITS,LAND_SQUARE_FEET,GROSS_SQUARE_FEET,YEAR_BUILT,TAX_CLASS_AT_TIME_OF_SALE,BUILDING_CLASS_AT_TIME_OF_SALE,SALE_PRICE,SALE_DATE,ID
0,Staten Island,ANNADALE,01 ONE FAMILY HOMES,1,5402,17,A2,6 WEAVER STREET,,10312,...,0,1,10500.0,1964.0,1980,1,A2,720000,2004-07-15,9d55705e7d8e20ff381a616aa0b8927e
1,Staten Island,ANNADALE,01 ONE FAMILY HOMES,1,5406,23,A1,1666 ARDEN AVE,,10312,...,0,1,5000.0,1824.0,1950,1,A1,455000,2004-08-13,d9510e7eb008a810c1c7353a7d93cf8f
2,Staten Island,ANNADALE,01 ONE FAMILY HOMES,1,5407,36,A1,183 BATHGATE STREET,,10312,...,0,1,3700.0,4400.0,2004,1,A1,0,2004-10-13,ac0ad2a166fbfb40447e69154c56addf
3,Staten Island,ANNADALE,01 ONE FAMILY HOMES,1,5425,31,A2,7 SANDGAP STREET,,10312,...,0,1,2500.0,624.0,1925,1,A2,185000,2004-06-16,22b4a0458548d01b6a400af41375adbe
4,Staten Island,ANNADALE,01 ONE FAMILY HOMES,1,6205,4,A5,111 EAGAN AVENUE,,10312,...,0,1,1845.0,1854.0,1986,1,A5,325000,2004-05-26,79a3f29c301673419baffef5f0145d49

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11942 entries, 0 to 11941
Data columns (total 21 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   BOROUGH                         11942 non-null  string
 1   NEIGHBORHOOD                    11942 non-null  string
 2   BUILDING_CLASS_CATEGORY         11942 non-null  object
 3   TAX_CLASS_BEFORE_SALE           11942 non-null  object
 4   BLOCK                           11942 non-null  int64
 5   LOT                             11942 non-null  int64
 6   BUILDING_CLASS_BEFORE_SALE      11942 non-null  object
 7   ADDRESS                         11942 non-null  string
 8   APARTMENT_NUMBER                11942 non-null  object
 9   ZIP_CODE                        11942 non-null  int64
 10  RESIDENTIAL_UNITS               11942 non-null  int32
 11  COMMERCIAL_UNITS                11942 non-null  int32
 12  TOTAL_UNITS                     11942 non-null  int32
 13  LAND_SQUARE_FEET                11942 non-null  float64
 14  GROSS_SQUARE_FEET               11942 non-null  float64
 15  YEAR_BUILT                      11942 non-null  int64
 16  TAX_CLASS_AT_TIME_OF_SALE       11942 non-null  object
 17  BUILDING_CLASS_AT_TIME_OF_SALE  11942 non-null  object
 18  SALE_PRICE                      11942 non-null  int64
 19  SALE_DATE                       11942 non-null  datetime64[ns]
 20  ID                              11942 non-null  string
dtypes: datetime64[ns](1), float64(2), int32(3), int64(5), object(6), string(4)
memory usage: 1.8+ MB

In [5]:
df.loc[df['ZIP_CODE'] == 0]

Empty DataFrame
Columns: [BOROUGH, NEIGHBORHOOD, BUILDING_CLASS_CATEGORY, TAX_CLASS_BEFORE_SALE, BLOCK, LOT, BUILDING_CLASS_BEFORE_SALE, ADDRESS, APARTMENT_NUMBER, ZIP_CODE, RESIDENTIAL_UNITS, COMMERCIAL_UNITS, TOTAL_UNITS, LAND_SQUARE_FEET, GROSS_SQUARE_FEET, YEAR_BUILT, TAX_CLASS_AT_TIME_OF_SALE, BUILDING_CLASS_AT_TIME_OF_SALE, SALE_PRICE, SALE_DATE, ID]
Index: []

[0 rows x 21 columns]